### ISSUE TITLE
Implement pairing code

### ISSUE THREAD

**Issue by unknownconstant** [unknownconstant/ArduinoBLE#9]
Implement callback to expose pairing value to the Arduino sketch, and allow developer to implement confirm / reject behaviour.

**Comment by eltos** [comment]
This will also require
- [ ] a method to set the [IO Capabilities](https://github.com/unknownconstant/ArduinoBLE/blob/283038fe416d1af16fee6493142452dd05f9b65a/src/utility/L2CAPSignaling.h#L44-L48)
- [ ] Implementation of the different methods to be used in Phase 2
  - [x] Just Works
  - [ ] Numeric Comparison
  - [ ] Passkey Entry
  - [ ] Out Of Band (OOB)

**Comment by unknownconstant** [comment]
@eltos The IO Capabilities could be set based off whether the callbacks have been implemented? i.e. if there is a callback for the pairing value then set the iocap to display, and if there is a confirm / reject implemented then set the input to yes/no etc.

Numeric comparison should be straightforward to implement, but I've not got capacity to do Passkey or Oob at present
